version: "3"

services:
  video-api:
    build: 
      context: backend/video_api
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  streaming-frontend:
    build:
      context: streaming_frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongdb-data:/data/db